Atoms/Inputの作成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #13
Opened 2024-05-18 09:51 UTC by Akidesign

2024-05-20 10:33 UTC, toma0705 requested changes
いくつかコメントしました。
確認をお願いします。

2024-05-20 10:33 UTC, toma0705 commented on src/components/Atoms/Input/index.jsx
> +const StyledInput = styled.div`
divからinputに修正をお願いします。

2024-05-20 10:33 UTC, toma0705 commented on src/components/Atoms/Input/index.jsx
> +  background-color: ${COLOR.BLACk};
BLACKのｋが小文字になっています。

2024-05-20 10:33 UTC, toma0705 commented on src/components/Atoms/Input/index.jsx
> +  color: ${COLOR.LIGHT_GRAY} ${TEXT.S};
見た目の修正をお願いします。
・width
・outlineを消す
・選択状態の時、枠の周りが光るのを消す

2024-05-20 11:46 UTC, Akidesign commented
styled.divを styled.inputに変更
BLACkをBLACKに変更
width: 232px; を追加
outlineを消すためにoutline: none;を追加
選択状態の時に枠の周りが光るのを消すためにborder: none;を追加しました。
選択状態の時に枠の周りが光るのを消すというのが出来ているか不安です。
レビューをお願いします。

2024-05-22 08:04 UTC, toma0705 commented
Widthの見た目がお手本と異なると思ったらfigmaに232pxと書かれていましたね💦
figma通りにできていて素晴らしいと思います！
しかし、232pxだとWindowの大きさを変えたときに困るので値を100%にした方がいいかもしれません。
最終判断は２次レビューにお願いしたいと思います。ひとまず、1次レビューOKです！

2024-05-22 08:51 UTC, higashiji2000 requested changes

2024-05-22 08:51 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  width: 232px;
> 要素の横幅は、親要素の幅いっぱいに広がるようにしましょう。

[課題ページ](https://shinonome-inc.notion.site/Atoms-Input-a0d6406839cd40459ef5ebcc43d76163)の上の方に上記のように書いてあるので、そのように修正をお願いします。
わかりづらくてすみません 🙏

2024-05-22 08:51 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  color: ${COLOR.LIGHT_GRAY} ${TEXT.S};
<img width="303" alt="image" src="https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/f6dba5c1-3a71-456c-8978-45117c998970">
color がうまい感じになっていないので、 figma やお手本通りになるように修正お願いします。

2024-05-24 16:23 UTC, higashiji2000 requested changes

2024-05-24 16:23 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  gap: 10px;
![image](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/a90a05ae-989f-4977-ba46-89638218e476)
gap は不要なので、削除してしまってください。
検証ツールを開くと、画像のように無効なプロパティは薄く表示されますので参考になるかと思います。

2024-05-24 16:23 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  color: ${COLOR.LIGHT_GRAY} ${TEXT.S};
```suggestion
  color: ${COLOR.WHITE};
```
背景が黒いので、文字を白にする必要があります。
このように修正していただければ白くなるかと思います！

2024-05-24 16:23 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  };
```suggestion
  const handleKeyDown = (e) => {
    if (e.key !== "Enter") return;
    e.target.blur();
  };
```
こんな感じで修正していただけると良いかと！

2024-05-24 16:23 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +      onkeyDown={handleKeyDown}
```suggestion
      onKeyDown={handleKeyDown}
```
属性名が間違っているようです。
こうするとキー押下時にイベントハンドラが呼ばれるようになります。

2024-05-25 00:21 UTC, Akidesign commented
ありがとうございます。
gapを削除・colorをlight_grayからwhiteに変更・onEditCompleteからe.target.blurに変更・onkeyDownからonKeyDownに属性名を変更しました。

2024-05-28 16:41 UTC, higashiji2000 approved these changes

2024-05-28 22:53 UTC, merged