Molecules/Taskの作成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #15
Opened 2024-05-28 23:15 UTC by Akidesign

Molecules/Taskの作成のレビューをお願いします。

2024-05-29 13:01 UTC, Akidesign commented
defaultIsEditingをfalseをtrueに変更・StyledNameAndButtonContainerを画面いっぱいに広げるためにwidth: 100%;を追加しました。

2024-05-31 08:17 UTC, toma0705 commented
defaultIsEditingをfalseをtrueに変更はOKです！
width: 100%がこちらに反映されていないよう気がします。確認をお願いします。

2024-05-31 14:20 UTC, Akidesign commented
width: 100%;が反映されるように変更しました。
出来ていますか？

2024-06-01 03:11 UTC, toma0705 commented
できています！
１次レビューOKです。

2024-06-02 14:15 UTC, higashiji2000 requested changes
<img width="329" alt="image" src="https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/10d0dfa1-fecc-45a1-a582-7cca6bcdb3cd">
テキストが長い時に省略されず全て出てしまっているので、お手本通りに省略されるように修正をお願いします。

2024-06-03 01:55 UTC, Akidesign commented
テキストが横いっぱいに広がるように変更しました。
ですが正直できているか不安です。

2024-06-08 06:34 UTC, Higashiji requested changes

2024-06-08 06:34 UTC, Higashiji commented on src/components/Molecules/Task/index.jsx
> +  flex: 1;
```suggestion
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
```

説明がわかりづらくすみません 🙏 
このようにすると、[お手本](https://shinonome.io/frontend-basic-2022-todoapp/)通りに長いテキストが省略されるようになります。

2024-06-08 06:35 UTC, Higashiji commented on src/components/Molecules/Task/index.jsx
> +  flex: 1;
Before:  
![image](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/6c4e839e-d5a5-4c89-aae1-a66f8604ad56)

After:  
![image](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/9f47e79b-beb5-4320-866f-923da00339e1)

2024-06-09 12:13 UTC, Akidesign commented
ありがとうございます。
テキストが横いっぱいに広がるようにするためにflex: 1;を削除しました。

2024-06-09 13:08 UTC, Akidesign commented
画像は表示されています。
ただ修正箇所が違っていたため、修正しなおしました。
overflowとtext-overflowだけではうまく出来なかったため、white-spaceを追加しました。

2024-06-12 04:11 UTC, Higashiji requested changes

2024-06-12 04:11 UTC, Higashiji commented on src/components/Molecules/Task/index.jsx
> +  text-overflow: ellipsis;
```suggestion
  text-overflow: ellipsis;
  flex: 1;
```

非編集時にテキスト部分が幅いっぱいに広がるように修正をお願いします :pray:

<img width="330" alt="image" src="https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/5ed3e075-9b5b-4070-b1dd-f7df87dadc79">

<img width="330" alt="image" src="https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/2848ae1f-afd8-47fe-a308-7544fc30a046">

2024-06-12 04:36 UTC, Akidesign commented
テキスト部分が幅いっぱいに広がるようにwidth: 100%;を追加しました。

2024-06-12 04:39 UTC, Higashiji approved these changes
LGTM 🎉

2024-06-12 04:48 UTC, merged