Organisms/TodoCardの作成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #17
Opened 2024-06-12 05:33 UTC by Akidesign

レビューをお願いします。
コミットが多いですが、ブランチを切る場所を間違えて新しく作り直したためです。
見ていただきたいコミットは最新４つです。（古い方５つは無視してください。）

2024-06-15 11:10 UTC, toma0705 requested changes
いい感じです！
１点だけ修正をお願いします。

2024-06-15 11:10 UTC, toma0705 commented on src/components/Organisms/TodoCard/index.jsx
> +            defaultValue={task.initializing}
新しいタスクリストを追加したときのデフォルトが非編集状態でした。
41行目の変数名が原因だと思います。

2024-06-15 16:08 UTC, Akidesign commented
変数名をdefaultValueをdefaultIsEditingに変更しました。

2024-06-15 16:15 UTC, toma0705 commented
1次レビューOKです！🙆🏻

2024-06-16 04:18 UTC, Higashiji approved these changes

2024-06-16 04:18 UTC, Higashiji commented on src/components/Organisms/TodoCard/index.jsx
> +        const newTaskList = [...(taskList || [])];
```suggestion
        const newTaskList = [...taskList];
```
`taskList` は 空配列 で初期化しているので、↑の書き方で問題ないと思います。

2024-06-16 13:43 UTC, merged