ひとまず完成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #19
Opened 2024-06-25 13:20 UTC by Akidesign

画面に表示されないが、レビューを出すためコミットしました。
状態としては、localhost:8080は開くが、画面が黒くなり何も表示されないという状態です。
依存関係に関するエラーが出ていたため、node_modulesとyarn.lockを再インストールしましたが、修正されません。

2024-06-25 13:26 UTC, Akidesign commented
画面に表示されないが、レビューを出すためコミットしました。
状態としては、localhost:8080は開くが、画面が黒くなり何も表示されないという状態です。
依存関係に関するエラーが出ていたため、node_modulesとyarn.lockを再インストールしましたが、修正されません。

2024-06-27 02:00 UTC, Akidesign commented
表示されない状態を直すためpackage.jsonファイルの差分の修正・node_modulesの再インストールをしました。
現在は表示されるようになったため、レビューを出します。

2024-06-30 10:57 UTC, toma0705 requested changes
いい感じです！
1つだけ修正をお願いします。

2024-06-30 10:58 UTC, toma0705 commented
![スクリーンショット 2024-06-30 195327](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/137295156/a0335d92-98c9-4055-a9fd-1840ad0e9b33)
![スクリーンショット 2024-06-30 195455](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/137295156/195360ca-8a2e-4d1e-afc9-bf710a6c83c9)
模範のようにタスク同士の間を少し開けてほしいです。

2024-07-02 02:17 UTC, Akidesign commented
& > * { margin top: 10px; }を追加し、余白を指定しました。

2024-07-02 12:15 UTC, toma0705 commented
入れ子セレクター(&)を使ったんですね！素晴らしいと思います！私も勉強になりました。１次レビューOKです！

2024-07-03 04:35 UTC, Higashiji approved these changes

2024-07-03 04:35 UTC, Higashiji commented on src/components/Organisms/TodoCard/index.jsx
> +  }
![badge-fyi](https://img.shields.io/badge/review-FYI-white)　（参考までに共有，アクションは不要）

```suggestion
  padding-top: 10px;
  gap: 10px;
```
個人的には、要素間の余白は `gap` を使う方が好きです！
`margin` は相殺が発生する可能性がありますし、可読性も `gap` の方が高いかと思います。

とはいえ、未知の要素を使っていく姿勢はめちゃくちゃ素敵だと思います 🎉

2024-07-03 05:38 UTC, Akidesign commented
ありがとうございます。
いろいろやってみようと思います。

2024-07-03 05:39 UTC, Akidesign commented
Github Pages の設定
設定ができておらず、リンクを貼っていなかったため、ここで貼る。（挙動は確認済み）
https://akidesign.github.io/aki-fukushima-frontend-basic-2022-todoapp/

2024-07-03 05:41 UTC, merged