Alertの作成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #21
Opened 2024-07-19 12:45 UTC by Akidesign

2024-08-02 12:11 UTC, toma0705 requested changes
難しいalertの表示ができていて素晴らしいと思いました！
細かい点のレビューをしたので修正をお願いします。

2024-08-02 12:11 UTC, toma0705 commented on src/components/Atoms/Alert/index.jsx
> +  transform: translate(-50%, 0);
縦にもtranslateの指定をお願いします。(alertActiveを使うとうまくいくかも...)

2024-08-02 12:11 UTC, toma0705 commented on src/components/Atoms/Alert/index.jsx
> +  max-width: 360px;
paddingのwidthも入れた値をmax-widthにしてほしいです。

2024-08-03 07:11 UTC, Akidesign commented
縦にalertActiveを使い、translateの指定をしました。またpaddingのwidthも入れた値をmax-widthにしました。
出来ていますか？

2024-08-11 01:17 UTC, Akidesign commented
width : 100%;を追加しmax-widthは400pxに修正・alertActiveがtrueの時もwidth : 100%;を追加しmax-widthは400pxに修正しました。出来ていますか？

2024-08-11 03:20 UTC, toma0705 commented on src/components/Atoms/Alert/index.jsx
> +    transform: translate(-50%, 100%);
ここでもAlertが出てくるときにスライドするようにお願いします。

2024-08-11 03:21 UTC, toma0705 reviewed
いい感じだと思います！最後に一つだけ修正をお願いします。

2024-08-11 05:30 UTC, Akidesign commented
Alertが出てくるときにスライドするように修正しました。出来ていますか？

2024-08-12 10:36 UTC, toma0705 commented
いい感じだと思います！

2024-08-19 14:43 UTC, Higashiji approved these changes
LGTMです 🎉

2024-08-19 14:43 UTC, Higashiji commented on src/components/Atoms/Alert/index.jsx
> +import BREAKPOINT from "../../../variables/breakpoint"; // BREAKPOINTをインポート
コード上自明な内容については、コメントを書かないのが望ましいとされています。
コメントは、コード上から読み取れない「Why」を記述するよう意識するのが良いかと思います。

2024-08-19 14:43 UTC, Higashiji commented on src/components/Atoms/Alert/index.jsx
> +`;
```suggestion
const AlertText = styled.div`
  font-size: 14px;
  color: ${COLOR.WHITE};
  font-family: ${FONTFAMILY.NOTO_SANS};
`;
```
個人的にはこんな感じのコンポーネント名の方がしっくりきます

2024-08-20 14:18 UTC, merged