Atoms/editbuttonを作成しました。
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #3
Opened 2024-05-03 02:09 UTC by Akidesign

2024-05-04 16:16 UTC, toma0705 requested changes
コードがとても見やすくて素晴らしいです！
１つだけ修正をよろしくお願いします。

2024-05-04 16:16 UTC, toma0705 commented on src/components/Atoms/EditButton/index.jsx
> +      <img src={pencil} />
"img"はHTMLの予約語であるためstyled-componentsが適切に処理できないようです。なので別の変数名にしてみてください。

2024-05-04 16:16 UTC, toma0705 commented on src/components/Atoms/EditButton/index.jsx
> +const img = styled.img`
ここも同じ変数名に変えてください。

2024-05-05 00:41 UTC, Akidesign commented
imgをpencilbuttonという名前に変更しました。

2024-05-05 23:51 UTC, higashiji2000 requested changes

2024-05-05 23:51 UTC, higashiji2000 commented on src/components/Atoms/EditButton/index.jsx
> +import pencil from "../../../assets/svg/pencil.svg";
![image](https://github.com/Akidesign/aki-fukushima-frontend-basic-2022-todoapp/assets/83479175/5bbc6d34-b014-4187-a128-4b42494d536f)
Chromatic を見ると storybook に画像が表示されていないのですが、そちらではちゃんと表示されていますか？
下記のコンポーネント名が原因かもしれません。

2024-05-05 23:51 UTC, higashiji2000 commented on src/components/Atoms/EditButton/index.jsx
> +`;
```suggestion
      <PencilButton src={pencil} />
    </Button>
  );
};

const Button = styled.button`
  cursor: pointer;
  display: flex;
  width: 20px;
  height: 20px;
  border: 0px;
  justify-content: center;
  align-items: center;
  background-color: ${COLOR.LIGHT_GRAY_TRANSPARENT};
  :hover {
    background-color: ${COLOR.LIGHT_GRAY_TRANSLUCENT};
    border-radius: 20px;
  }
`;

const PencilButton = styled.img`
  width: 20px;
  height: 20px;
`;
```

React のコンポーネントはアッパーキャメルケース（パスカルケース）で命名することになっているので、上記のように修正お願いします。
参考：https://www.wakuwakubank.com/posts/804-it-naming-convention/

2024-05-06 00:13 UTC, Akidesign commented
変数名をパスカルケースになるように変更しました

2024-05-06 00:17 UTC, higashiji2000 reviewed
先頭も大文字でお願いします 🧯

2024-05-06 00:17 UTC, higashiji2000 commented on src/components/Atoms/EditButton/index.jsx
> +const pencilButton = styled.img`
```suggestion
      <PencilButton src={pencil} />
    </Button>
  );
};

const Button = styled.button`
  cursor: pointer;
  display: flex;
  width: 20px;
  height: 20px;
  border: 0px;
  justify-content: center;
  align-items: center;
  background-color: ${COLOR.LIGHT_GRAY_TRANSPARENT};
  :hover {
    background-color: ${COLOR.LIGHT_GRAY_TRANSLUCENT};
    border-radius: 20px;
  }
`;

const PencilButton = styled.img`
```

2024-05-06 00:20 UTC, higashiji2000 approved these changes
LGTM 🚇

2024-05-06 00:25 UTC, merged