Atoms/AddTaskButtonの作成
Akidesign/aki-fukushima-frontend-basic-2022-todoapp pull request #5
Opened 2024-05-08 03:06 UTC by Akidesign

2024-05-08 04:25 UTC, Akidesign commented
atoms/AddTaskButtonを作成しました。
テキストの見た目がお手本と違う気がしています。
レビューをお願いします。

2024-05-10 10:53 UTC, toma0705 requested changes

2024-05-10 10:53 UTC, toma0705 commented on src/components/Atoms/AddTaskButton/index.jsx
> +  font-family: ${FONTFAMILY.NOTO_SANS_JP};
ここがうまく反映されていません。variablesのfont_family.jsファイルをよく確認すると解決できると思います！

2024-05-10 11:22 UTC, Akidesign commented
ありがとうございます。
フォント名称を変更したらうまく行きました。

2024-05-11 16:14 UTC, higashiji2000 requested changes

2024-05-11 16:14 UTC, higashiji2000 commented on src/components/Atoms/AddTaskButton/index.stories.jsx
> +    onclick: () => console.log("clicked"),
```suggestion
    onClick: () => console.log("clicked"),
```

細かいところですが、現状Storybookでクリックしてもログが表示されないため修正をお願いします。

2024-05-12 00:18 UTC, higashiji2000 approved these changes
LGTM 🪮

2024-05-12 00:25 UTC, merged